package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.pointlion.sys.mvc.common.base.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowModelnode<M extends BaseOaCustomflowModelnode<M>> extends BaseModel<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setModelid(java.lang.String modelid) {
        set("modelid", modelid);
    }

    public java.lang.String getModelid() {
        return getStr("modelid");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getName() {
        return getStr("name");
    }

    public void setSequence(java.lang.Integer sequence) {
        set("sequence", sequence);
    }

    public java.lang.Integer getSequence() {
        return getInt("sequence");
    }

    public void setApprovaltype(java.lang.Integer approvaltype) {
        set("approvaltype", approvaltype);
    }

    public java.lang.Integer getApprovaltype() {
        return getInt("approvaltype");
    }
    public void setApprovaluserid(java.lang.String approvaluserid) {
        set("approvaluserid", approvaluserid);
    }

    public java.lang.String getApprovaluserid() {
        return getStr("approvaluserid");
    }

    public void setNextmodelnodeid(java.lang.String nextmodelnodeid) {
        set("nextmodelnodeid", nextmodelnodeid);
    }

    public java.lang.String getNextmodelnodeid() {
        return getStr("nextmodelnodeid");
    }

}
