package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserSign<M extends BaseSysUserSign<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSignImg(java.lang.String signImg) {
		set("sign_img", signImg);
	}
	
	public java.lang.String getSignImg() {
		return getStr("sign_img");
	}

	public void setSignLocal(java.lang.String signLocal) {
		set("sign_local", signLocal);
	}
	
	public java.lang.String getSignLocal() {
		return getStr("sign_local");
	}

	public void setSignFile(byte[] signFile) {
		set("sign_file", signFile);
	}
	
	public byte[] getSignFile() {
		return get("sign_file");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setUpdatetime(java.lang.String updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.lang.String getUpdatetime() {
		return getStr("updatetime");
	}

	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}

	public void setTaskid(java.lang.String taskid) { set("taskid", taskid); }

	public java.lang.String getTaskid() { return getStr("taskid"); }
}
