package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysTemplateparam<M extends BaseSysTemplateparam<M>> extends Model<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getName() {
        return getStr("name");
    }

    public void setParam(java.lang.String param) {
        set("param", param);
    }

    public java.lang.String getParam() {
        return getStr("param");
    }

    public void setModule(java.lang.String module) {
        set("module", module);
    }

    public java.lang.String getModule() {
        return getStr("module");
    }

}
