package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowType<M extends BaseOaCustomflowType<M>> extends Model<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getName() {
        return getStr("name");
    }

    public void setParent(java.lang.String parent) {
        set("parent", parent);
    }

    public java.lang.String getParent() {
        return getStr("parent");
    }

    public void setLevel(java.lang.Integer level) {
        set("level", level);
    }

    public java.lang.Integer getLevel() {
        return getInt("level");
    }

    public void setState(java.lang.Integer state) {
        set("state", state);
    }

    public java.lang.Integer getState() {
        return getInt("state");
    }

    public void setCreateUser(java.lang.String createUser) {
        set("create_user", createUser);
    }

    public java.lang.String getCreateUser() {
        return getStr("create_user");
    }

    public void setCreateTime(java.lang.String createTime) {
        set("create_time", createTime);
    }

    public java.lang.String getCreateTime() {
        return getStr("create_time");
    }

}
