package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowFlowmodel<M extends BaseOaCustomflowFlowmodel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setType1(java.lang.String type1) {
		set("type_1", type1);
	}
	
	public java.lang.String getType1() {
		return getStr("type_1");
	}

	public void setType2(java.lang.String type2) {
		set("type_2", type2);
	}
	
	public java.lang.String getType2() {
		return getStr("type_2");
	}

	public void setType3(java.lang.String type3) {
		set("type_3", type3);
	}
	
	public java.lang.String getType3() {
		return getStr("type_3");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setNodeSum(java.lang.Integer nodeSum) {
		set("node_sum", nodeSum);
	}
	
	public java.lang.Integer getNodeSum() {
		return getInt("node_sum");
	}

	public void setExecuteSum(java.lang.Integer executeSum) { set("execute_sum", executeSum); }

	public java.lang.Integer getExecuteSum() { return getInt("execute_sum"); }

	public void setVisibleOrg(java.lang.String visibleOrg) { set("visible_org", visibleOrg); }

	public java.lang.String getVisibleOrg() { return get("visible_org"); }

}
