package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowJoinlty<M extends BaseOaCustomflowJoinlty<M>> extends Model<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setCreateUser(java.lang.String createUser) {
        set("create_user", createUser);
    }

    public java.lang.String getCreateUser() {
        return getStr("create_user");
    }

    public void setCreateTime(java.lang.String createTime) {
        set("create_time", createTime);
    }

    public java.lang.String getCreateTime() {
        return getStr("create_time");
    }

    public void setRequestContent(java.lang.String requestContent) {
        set("request_content", requestContent);
    }

    public java.lang.String getRequestContent() {
        return getStr("request_content");
    }

    public void setResponseContent(java.lang.String responseContent) {
        set("response_content", responseContent);
    }

    public java.lang.String getResponseContent() {
        return getStr("response_content");
    }

    public void setAcceptUser(java.lang.String acceptUser) {
        set("accept_user", acceptUser);
    }

    public java.lang.String getAcceptUser() {
        return getStr("accept_user");
    }

    public void setResponseTime(java.lang.String responseTime) {
        set("response_time", responseTime);
    }

    public java.lang.String getResponseTime() {
        return getStr("response_time");
    }

    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }

    public java.lang.Integer getStatus() {
        return getInt("status");
    }
    public void setCaseId(java.lang.String caseid) {
        set("caseid", caseid);
    }
    public java.lang.String getCaseId() {
        return getStr("caseid");
    }

    public void setRequestId(java.lang.String requestid) {
        set("request_id", requestid);
    }
    public java.lang.String getRequestId() {
        return getStr("request_id");
    }

    public void setResponseId(java.lang.String responseid) {
        set("response_id", responseid);
    }
    public java.lang.String getResponseId() {
        return getStr("response_id");
    }

}
