package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowCase<M extends BaseOaCustomflowCase<M>> extends Model<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setModelid(java.lang.String modelid) {
        set("modelid", modelid);
    }

    public java.lang.String getTablename() {
        return getStr("tablename");
    }
    public void setTablename(java.lang.String tablename) {
        set("tablename", tablename);
    }

    public java.lang.String getDefkey() {
        return getStr("defkey");
    }
    public void setDefkey(java.lang.String defkey) {
        set("defkey", defkey);
    }

    public java.lang.String getModelid() {
        return getStr("modelid");
    }


    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }

    public java.lang.Integer getStatus() {
        return getInt("status");
    }

    public void setCurrentmodelnodeid(java.lang.String currentmodelnodeid) {
        set("currentmodelnodeid", currentmodelnodeid);
    }

    public java.lang.String getCurrentmodelnodeid() {
        return getStr("currentmodelnodeid");
    }

    public void setCreateuser(java.lang.String createuser) {
        set("createuser", createuser);
    }

    public java.lang.String getCreateuser() {
        return getStr("createuser");
    }

    public void setCreatetime(java.lang.String createtime) {
        set("createtime", createtime);
    }

    public java.lang.String getCreatetime() {
        return getStr("createtime");
    }
    public void setFileUser(java.lang.String fileuser) {
        set("fileuser", fileuser);
    }

    public java.lang.String getFileUser() {
        return getStr("fileuser");
    }
    public void setFileTime(java.lang.String filetime) {
        set("filetime", filetime);
    }

    public java.lang.String getFileTime() {
        return getStr("filetime");
    }
}
