package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaPermissionTable<M extends BaseOaPermissionTable<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setGroupid(java.lang.String groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.String getGroupid() {
		return getStr("groupid");
	}

	public void setTablename(java.lang.String tablename) {
		set("tablename", tablename);
	}
	
	public java.lang.String getTablename() {
		return getStr("tablename");
	}

	public void setTablevalue(java.lang.String tablevalue) {
		set("tablevalue", tablevalue);
	}
	
	public java.lang.String getTablevalue() {
		return getStr("tablevalue");
	}

	public void setTableid(java.lang.String tableid) {
		set("tableid", tableid);
	}
	
	public java.lang.String getTableid() {
		return getStr("tableid");
	}

	public void setDefkey(java.lang.String defkey) {
		set("defkey", defkey);
	}
	
	public java.lang.String getDefkey() {
		return getStr("defkey");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

}
