package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMobileVersion<M extends BaseSysMobileVersion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setUpdatetime(java.lang.String updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.lang.String getUpdatetime() {
		return getStr("updatetime");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}
	
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public void setIfPublish(java.lang.String ifPublish) {
		set("if_publish", ifPublish);
	}
	
	public java.lang.String getIfPublish() {
		return getStr("if_publish");
	}

	public void setIosUri(java.lang.String iosUri) {
		set("ios_uri", iosUri);
	}
	
	public java.lang.String getIosUri() {
		return getStr("ios_uri");
	}

	public void setAndroidUri(java.lang.String androidUri) {
		set("android_uri", androidUri);
	}
	
	public java.lang.String getAndroidUri() {
		return getStr("android_uri");
	}

}
