package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowCasenode<M extends BaseOaCustomflowCasenode<M>> extends Model<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setCaseid(java.lang.String caseid) {
        set("caseid", caseid);
    }

    public java.lang.String getCaseid() {
        return getStr("caseid");
    }

    public void setApprovaluserid(java.lang.String approvaluserid) {
        set("approvaluserid", approvaluserid);
    }

    public java.lang.String getApprovaluserid() {
        return getStr("approvaluserid");
    }

    public void setIsCommitCasenode(java.lang.Integer isCommitCasenode) {
        set("is_commit_casenode", isCommitCasenode);
    }

    public java.lang.Integer getIsCommitCasenode() {
        return getInt("is_commit_casenode");
    }

    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }

    public java.lang.Integer getStatus() {
        return getInt("status");
    }

    public void setModelnodeid(java.lang.String modelnodeid) {
        set("modelnodeid", modelnodeid);
    }

    public java.lang.String getModelnodeid() {
        return getStr("modelnodeid");
    }

    public void setCreatetime(java.lang.String createtime) {
        set("createtime", createtime);
    }

    public java.lang.String getCreatetime() {
        return getStr("createtime");
    }

}
