package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowCasenodeMapping<M extends BaseOaCustomflowCasenodeMapping<M>> extends Model<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setCasenodeid(java.lang.String casenodeid) {
        set("casenodeid", casenodeid);
    }

    public java.lang.String getCasenodeid() {
        return getStr("casenodeid");
    }

    public void setNextcasenodeid(java.lang.String nextcasenodeid) {
        set("nextcasenodeid", nextcasenodeid);
    }

    public java.lang.String getNextcasenodeid() {
        return getStr("nextcasenodeid");
    }

    public void setCreateTime(java.lang.String createTime) {
        set("create_time", createTime);
    }

    public java.lang.String getCreateTime() {
        return getStr("create_time");
    }

}
