package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysHrOrg<M extends BaseSysHrOrg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.String getOrgid() {
		return getStr("orgid");
	}

	public void setOrgname(java.lang.String orgname) {
		set("orgname", orgname);
	}
	
	public java.lang.String getOrgname() {
		return getStr("orgname");
	}

	public void setOrgParent(java.lang.String orgParent) {
		set("org_parent", orgParent);
	}
	
	public java.lang.String getOrgParent() {
		return getStr("org_parent");
	}

	public void setGroupid(java.lang.String groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.String getGroupid() {
		return getStr("groupid");
	}

}
