package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowComment<M extends BaseOaCustomflowComment<M>> extends Model<M> implements IBean {

    public void setId(java.lang.String id) {
        set("id", id);
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public void setCasenodeid(java.lang.String casenodeid) {
        set("casenodeid", casenodeid);
    }

    public java.lang.String getCasenodeid() {
        return getStr("casenodeid");
    }

    public void setApprovalOpinion(java.lang.String approvalOpinion) {
        set("approval_opinion", approvalOpinion);
    }

    public java.lang.String getApprovalOpinion() {
        return getStr("approval_opinion");
    }

    public void setHandleOpinion(java.lang.String handleOpinion) {
        set("handle_opinion", handleOpinion);
    }

    public java.lang.String getHandleOpinion() {
        return getStr("handle_opinion");
    }

    public void setSignAddress(java.lang.String signAddress) {
        set("sign_address", signAddress);
    }

    public java.lang.String getSignAddress() {
        return getStr("sign_address");
    }

    public void setApprovalTime(java.lang.String approvalTime) {
        set("approval_time", approvalTime);
    }

    public java.lang.String getApprovalTime() {
        return getStr("approval_time");
    }

    public void setApprovalState(java.lang.String approvalState) {
        set("approval_state", approvalState);
    }

    public java.lang.String getApprovalState() {
        return getStr("approval_state");
    }

}
