package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaCustomflowModelOrg<M extends BaseOaCustomflowModelOrg<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}

	public void setModelid(String modelid) {
		set("modelid", modelid);
	}
	
	public String getModelid() {
		return getStr("modelid");
	}

	public void setOrgid(String orgid) {
		set("orgid", orgid);
	}
	
	public String getOrgid() {
		return getStr("orgid");
	}

	public void setUpdateuser(String updateuser) {
		set("updateuser", updateuser);
	}
	
	public String getUpdateuser() {
		return getStr("updateuser");
	}

	public void setUpdatetime(String updatetime) {
		set("updatetime", updatetime);
	}
	
	public String getUpdatetime() {
		return getStr("updatetime");
	}

}
