package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaPermissionGroup<M extends BaseOaPermissionGroup<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	public void setAuthname(java.lang.String authname) {
		set("authname", authname);
	}
	
	public java.lang.String getAuthname() {
		return getStr("authname");
	}

	public void setUpdatetime(java.lang.String updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.lang.String getUpdatetime() {
		return getStr("updatetime");
	}

	public void setRoleid(java.lang.String roleid) {
		set("roleid", roleid);
	}
	
	public java.lang.String getRoleid() {
		return getStr("roleid");
	}

	public void setRolename(java.lang.String rolename) {
		set("rolename", rolename);
	}
	
	public java.lang.String getRolename() {
		return getStr("rolename");
	}

	public void setControllerid(java.lang.String controllerid) {
		set("controllerid", controllerid);
	}
	
	public java.lang.String getControllerid() {
		return getStr("controllerid");
	}

	public void setControllername(java.lang.String controllername) {
		set("controllername", controllername);
	}
	
	public java.lang.String getControllername() {
		return getStr("controllername");
	}

}
