package com.pointlion.sys.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOaPicture<M extends BaseOaPicture<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setImgurl(java.lang.String imgurl) {
		set("imgurl", imgurl);
	}
	
	public java.lang.String getImgurl() {
		return getStr("imgurl");
	}

	public void setCreatedate(java.lang.String createdate) {
		set("createdate", createdate);
	}
	
	public java.lang.String getCreatedate() {
		return getStr("createdate");
	}

	public void setDefkey(java.lang.String defkey) {
		set("defkey", defkey);
	}
	
	public java.lang.String getDefkey() {
		return getStr("defkey");
	}

	public void setLinkid(java.lang.String linkid) {
		set("linkid", linkid);
	}
	
	public java.lang.String getLinkid() {
		return getStr("linkid");
	}

	public void setFormat(java.lang.String format) {
		set("format", format);
	}
	
	public java.lang.String getFormat() {
		return getStr("format");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

}
