package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaResGet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaApplyResGet extends BaseOaResGet<OaApplyResGet> {
	public static final OaApplyResGet dao = new OaApplyResGet().dao();
	public static final String tableName = "oa_apply_res_get";
}
