package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaApplyLeave extends BaseOaLeave<OaApplyLeave> {
	public static final String tableName = "oa_apply_leave";
	public static final OaApplyLeave dao = new OaApplyLeave().dao();
	/***
	 * 根据主键查询
	 */
	public OaApplyLeave getById(String id){
		return OaApplyLeave.dao.findById(id);
	}
}
