package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaApplyUseCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaApplyUseCar extends BaseOaApplyUseCar<OaApplyUseCar> {
	public static final OaApplyUseCar dao = new OaApplyUseCar().dao();
	public static final String tableName = "oa_apply_use_car"; 
	/***
	 * 根据主键查询
	 */
	public OaApplyUseCar getById(String id){
		return OaApplyUseCar.dao.findById(id);
	}
}
