package com.pointlion.sys.mvc.common.model;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import com.pointlion.sys.mvc.admin.sys.dataauth.SysDataAuthTranslator;
import com.pointlion.sys.mvc.common.model.base.BaseOaBumph;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaBumph extends BaseOaBumph<OaBumph> {
	public static final OaBumph dao = new OaBumph();
	public static final String tableName = "oa_bumph"; 
	
	/***
	 * 获取分页
	 */
	public Page<OaBumph> getPage(int pnum,int psize,String type){
		String dataAuth = SysDataAuthTranslator.me.translator(tableName);
		String sql = " from "+dataAuth+" b LEFT JOIN act_hi_procinst p ON b.proc_ins_id=p.ID_ WHERE 1=1 ";
		if(StrKit.notBlank(type)){
			sql = sql + " AND b.type='"+type+"' ";
		}
		sql = sql + " ORDER BY create_time DESC";
		return OaBumph.dao.paginate(pnum, psize, "select b.*,p.PROC_DEF_ID_ defid", sql);
	}
	
}
