package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseOaResDct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaResDct extends BaseOaResDct<OaResDct> {
	public static final String tableName = "oa_res_dct";
	public static final OaResDct dao = new OaResDct().dao();
}
