package com.pointlion.sys.mvc.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.pointlion.sys.mvc.admin.oa.common.CommonFlowController;
import com.pointlion.sys.mvc.common.model.base.BaseVTasklist;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VTasklist extends BaseVTasklist<VTasklist> {
	public static final VTasklist dao = new VTasklist();
	public static final String tableName = "v_tasklist";

	private Logger logger = LoggerFactory.getLogger(CommonFlowController.class);

	/***
	 * 查询流程待办任务
	 */
	public VTasklist getTaskRecord(String id){
		String sql = "SELECT * FROM "+tableName+" t WHERE t.TASKID='"+id+"'";
		logger.info(String.format("=================================\n%s\n=================================", sql));
		return VTasklist.dao.findFirst(sql);
	}
	
	public Record getActTaskById(String taskid){
		return Db.findFirst("select * from act_hi_taskinst t where t.id_='"+taskid+"'");
	}
}
